create table if not exists public.direct_messages (
    id bigint generated by default as identity primary key,
    content text not null,
    sender_id uuid references auth.users(id) on delete cascade not null,
    recipient_id uuid references auth.users(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    read_at timestamp with time zone
);

-- Enable RLS
alter table public.direct_messages enable row level security;

-- Create policies
create policy "Users can view their own messages"
    on public.direct_messages for select
    to authenticated
    using (auth.uid() = sender_id or auth.uid() = recipient_id);

create policy "Users can send messages"
    on public.direct_messages for insert
    to authenticated
    with check (auth.uid() = sender_id);

-- Set up realtime
alter publication supabase_realtime add table direct_messages; 