create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    content text not null,
    sender_id uuid references auth.users(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.messages enable row level security;

-- Create policies
create policy "Users can view all messages"
    on public.messages for select
    to authenticated
    using (true);

create policy "Users can insert their own messages"
    on public.messages for insert
    to authenticated
    with check (auth.uid() = sender_id);

-- Set up realtime
alter publication supabase_realtime add table messages; 